package com.langwuyue.orange.zookeeper;

public enum KeeperStateEnum {
    /** Unused, this state is never generated by the server */
    @Deprecated
    Unknown(-1),

    /** The client is in the disconnected state - it is not connected
     * to any server in the ensemble. */
    Disconnected(0),

    /** Unused, this state is never generated by the server */
    @Deprecated
    NoSyncConnected(1),

    /** The client is in the connected state - it is connected
     * to a server in the ensemble (one of the servers specified
     * in the host connection parameter during ZooKeeper client
     * creation). */
    SyncConnected(3),

    /**
     * Auth failed state
     */
    AuthFailed(4),

    /**
     * The client is connected to a read-only server, that is the
     * server which is not currently connected to the majority.
     * The only operations allowed after receiving this state is
     * read operations.
     * This state is generated for read-only clients only since
     * read/write clients aren't allowed to connect to r/o servers.
     */
    ConnectedReadOnly(5),

    /**
     * SaslAuthenticated: used to notify clients that they are SASL-authenticated,
     * so that they can perform Zookeeper actions with their SASL-authorized permissions.
     */
    SaslAuthenticated(6),

    /** The serving cluster has expired this session. The ZooKeeper
     * client connection (the session) is no longer valid. You must
     * create a new client connection (instantiate a new ZooKeeper
     * instance) if you with to access the ensemble. */
    Expired(-112),

    /**
     * The client has been closed. This state is never generated by
     * the server, but is generated locally when a client calls
     * {@link ZooKeeper#close()} or {@link ZooKeeper#close(int)}
     */
    Closed(7);

    private final int intValue;     // Integer representation of value
    // for sending over wire

    KeeperStateEnum(int intValue) {
        this.intValue = intValue;
    }

    public int getIntValue() {
        return intValue;
    }

    public static KeeperStateEnum fromInt(int intValue) {
        switch (intValue) {
        case -1:
            return KeeperStateEnum.Unknown;
        case 0:
            return KeeperStateEnum.Disconnected;
        case 1:
            return KeeperStateEnum.NoSyncConnected;
        case 3:
            return KeeperStateEnum.SyncConnected;
        case 4:
            return KeeperStateEnum.AuthFailed;
        case 5:
            return KeeperStateEnum.ConnectedReadOnly;
        case 6:
            return KeeperStateEnum.SaslAuthenticated;
        case -112:
            return KeeperStateEnum.Expired;
        case 7:
            return KeeperStateEnum.Closed;

        default:
            throw new RuntimeException("Invalid integer value for conversion to KeeperState");
        }
    }
}
