/*
 * Copyright (c) 2025 Liang.Zhong. All rights reserved.
 *
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.langwuyue.orange.redis.template.transaction;

import com.langwuyue.orange.redis.RedisValueTypeEnum;
import com.langwuyue.orange.redis.annotation.transaction.OrangeRedisTransactionClient;

/**
 * Specialized interface template for Redis Transaction operations with String values.
 * This template extends {@link JSONOperationsTemplate} with String-specific optimizations
 * for handling String data types.
 * 
 * <p>Key features:
 * <ul>
 *   <li>Optimized for String operations</li>
 *   <li>Direct String storage without JSON serialization overhead</li>
 *   <li>Atomic String operations with version control</li>
 * </ul>
 * 
 * <p>Implementation notes:
 * <ul>
 *   <li>Values are stored directly as Strings</li>
 *   <li>No serialization/deserialization overhead</li>
 *   <li>Maintains atomic operation guarantees</li>
 * </ul>
 * 
 * <p>Performance considerations:
 * <ul>
 *   <li>More efficient than JSON operations for simple String values</li>
 *   <li>Reduced memory usage due to direct String storage</li>
 *   <li>Lower latency for read/write operations</li>
 * </ul>
 * 
 * @author Liang.Zhong
 * @since 1.0.0
 * @see com.langwuyue.orange.redis.template.transaction.JSONOperationsTemplate
 * @see com.langwuyue.orange.redis.annotation.transaction.OrangeRedisTransactionClient
 * @see com.langwuyue.orange.redis.RedisValueTypeEnum#STRING
 */
@OrangeRedisTransactionClient(valueType = RedisValueTypeEnum.STRING)
public interface StringOperationsTemplate extends JSONOperationsTemplate<String> {

	/**
	 * Retrieves the current committed String value.
	 * 
	 * <p>This method overrides the generic {@link JSONOperationsTemplate#getValue()} method
	 * with a String-specific implementation. The default implementation returns null as a placeholder,
	 * as the actual implementation is provided at runtime through dynamic proxies generated by the
	 * Orange Redis framework.
	 * 
	 * <p>Implementation details:
	 * <ul>
	 *   <li>Returns value only if transaction is committed</li>
	 *   <li>Optimized for String values with direct retrieval</li>
	 *   <li>Respects the configured expiration time</li>
	 * </ul>
	 * 
	 * @return The current committed String value, or null if no committed value exists
	 */
	@Override
	default String getValue() {
		return null;
	}
	
}