/*
 * Copyright (c) 2025 Liang.Zhong. All rights reserved.
 *
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.langwuyue.orange.redis.mapping;

import java.util.Collection;
import java.util.List;

import com.langwuyue.orange.redis.executor.OrangeRedisExecutor;
import com.langwuyue.orange.redis.executor.cross.list.OrangeMoveByTimeoutArgExecutor;
import com.langwuyue.orange.redis.executor.cross.list.OrangeMoveExecutor;
import com.langwuyue.orange.redis.executor.cross.list.OrangeTimeLimitedMoveExecutor;
import com.langwuyue.orange.redis.listener.OrangeRedisMultipleSetIfAbsentListener;
import com.langwuyue.orange.redis.listener.OrangeRedisSetIfAbsentListener;
import com.langwuyue.orange.redis.logger.OrangeRedisLogger;
import com.langwuyue.orange.redis.operations.OrangeRedisListOperations;
import com.langwuyue.orange.redis.operations.OrangeRedisOperations;
import com.langwuyue.orange.redis.operations.OrangeRedisScriptOperations;
import com.langwuyue.orange.redis.template.NoTemplate;

/**
 * A specialized executor mapping for Redis List cross-key operations.
 * 
 * <p>This class extends {@link OrangeRedisAbstractExecutorsMapping} to provide
 * support for Redis List operations that span multiple keys. It registers various
 * executors that handle operations such as moving elements between lists and
 * operations with timeout constraints.
 * 
 * <p>The mapping uses {@link OrangeRedisListCrossKeyExecutorIdGenerator} to generate
 * unique identifiers for each executor based on the operation characteristics.
 * 
 * <p>This class is responsible for:
 * <ul>
 *   <li>Registering all supported Redis List cross-key operation executors</li>
 *   <li>Providing access to these executors through the mapping mechanism</li>
 *   <li>Ensuring proper initialization of executors with required dependencies</li>
 * </ul>
 *
 * @author Liang.Zhong
 * @since 1.0.0
 */
public class OrangeRedisListCrossKeyExecutorsMapping extends OrangeRedisAbstractExecutorsMapping {
	
	/**
	 * Constructs a new OrangeRedisListCrossKeyExecutorsMapping with the specified dependencies.
	 * 
	 * <p>This constructor initializes the mapping with all necessary components for
	 * handling Redis List cross-key operations.
	 *
	 * @param operations the Redis List operations interface providing core list functionality
	 * @param generator the executor ID generator specific to list cross-key operations
	 * @param listeners collection of listeners for single-key set-if-absent operations
	 * @param scriptOperations the Redis script operations interface for executing Lua scripts
	 * @param multipleListeners collection of listeners for multiple-key set-if-absent operations
	 * @param logger the logger instance for recording operation events and errors
	 */
	public OrangeRedisListCrossKeyExecutorsMapping(
		OrangeRedisListOperations operations,
		OrangeRedisListCrossKeyExecutorIdGenerator generator,
		Collection<OrangeRedisSetIfAbsentListener> listeners,
		OrangeRedisScriptOperations scriptOperations,
		Collection<OrangeRedisMultipleSetIfAbsentListener> multipleListeners,
		OrangeRedisLogger logger
	) {
		super(operations,generator,scriptOperations,listeners,multipleListeners,logger);
	}

	/**
	 * Registers all supported Redis List cross-key operation executors.
	 * 
	 * <p>This method extends the base implementation by registering executors specific
	 * to Redis List cross-key operations. Each executor is registered with a unique ID
	 * generated by the {@link OrangeRedisListCrossKeyExecutorIdGenerator}.
	 *
	 * @param executors the list to which executors will be added
	 * @param operations the Redis operations interface
	 * @param generator the executor ID generator
	 * @param scriptOperations the Redis script operations interface
	 * @param listeners collection of listeners for single-key set-if-absent operations
	 * @param multipleListeners collection of listeners for multiple-key set-if-absent operations
	 * @param logger the logger instance for recording operation events and errors
	 */
	@Override
	protected void registerExecutors(
		List<OrangeRedisExecutor> executors, 
		OrangeRedisOperations operations,
		OrangeRedisExecutorIdGenerator generator,
		OrangeRedisScriptOperations scriptOperations,
		Collection<OrangeRedisSetIfAbsentListener> listeners,
		Collection<OrangeRedisMultipleSetIfAbsentListener> multipleListeners,
		OrangeRedisLogger logger
	) {
		OrangeRedisListOperations listOperations = (OrangeRedisListOperations) operations;
		executors.add(new OrangeMoveExecutor(listOperations,generator));
		executors.add(new OrangeMoveByTimeoutArgExecutor(listOperations,generator));
		executors.add(new OrangeTimeLimitedMoveExecutor(listOperations,generator));
	}

	/**
	 * Returns the template class used by this executor mapping.
	 * 
	 * <p>This implementation returns {@link NoTemplate} class, indicating that
	 * this mapping does not use a specific template for its operations. The Redis
	 * List cross-key operations are handled directly by the registered executors
	 * without requiring an intermediate template.
	 *
	 * @return the {@link NoTemplate} class
	 */
	@Override
	protected Class<?> getTemplateClass() {
		return NoTemplate.class;
	}
}